POST http://127.0.0.1:5000/api/v1/todo/buy-apples
Content-Type: application/json

//{
//    "name" : "buy books"
//}

###

DELETE http://127.0.0.1:5000/api/v1/todo/study!!!
Content-Type: application/json


###
GET http://127.0.0.1:5000/api/v1/todos
Accept: application/json
